# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag, "jemoji"]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Minou alla carta"
description:	       "Created with Jekyll and the awesome Millennial theme"
#author:              "Minou Manafi Varkiani"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
